server:
  port: 5001


spring:
  application:
    name: producer
  cloud:
    stream:
      bindings:
        source1-out-0:
          destination: test1
      function:
        definition: source1
      kafka:
        binder:
          brokers: 192.168.95.1:9092
